"""
API框架核心模块
"""

from .app import APIFramework, get_app, get_api_framework
from .exceptions import (
    APIException,
    AuthenticationError,
    AuthorizationError,
    ValidationError,
    ResourceNotFoundError,
    RateLimitError,
    http_exception_handler,
    validation_exception_handler,
    api_exception_handler,
    general_exception_handler
)
from .middleware import (
    RequestIDMiddleware,
    TimingMiddleware,
    LoggingMiddleware,
    SecurityHeadersMiddleware,
    RateLimitMiddleware,
    RequestBodyMiddleware,
    ResponseBodyMiddleware
)
from .dependencies import (
    get_db,
    get_redis_client,
    get_config_manager,
    get_logger,
    get_current_user,
    get_current_active_user,
    get_current_admin_user,
    verify_permission,
    get_request_id,
    get_client_ip,
    get_user_agent,
    rate_limit_dependency,
    validate_pagination,
    get_api_version,
    get_service_status
)

__all__ = [
    'APIFramework',
    'get_app',
    'get_api_framework',
    'APIException',
    'AuthenticationError',
    'AuthorizationError',
    'ValidationError',
    'ResourceNotFoundError',
    'RateLimitError',
    'http_exception_handler',
    'validation_exception_handler',
    'api_exception_handler',
    'general_exception_handler',
    'RequestIDMiddleware',
    'TimingMiddleware',
    'LoggingMiddleware',
    'SecurityHeadersMiddleware',
    'RateLimitMiddleware',
    'RequestBodyMiddleware',
    'ResponseBodyMiddleware',
    'get_db',
    'get_redis_client',
    'get_config_manager',
    'get_logger',
    'get_current_user',
    'get_current_active_user',
    'get_current_admin_user',
    'verify_permission',
    'get_request_id',
    'get_client_ip',
    'get_user_agent',
    'rate_limit_dependency',
    'validate_pagination',
    'get_api_version',
    'get_service_status'
]