# 标准预设配置
# 适用于小型生产环境

# 继承默认配置
extends: "default"

# 系统配置
system:
  debug: false
  env: "production"

# 数据库配置
database:
  pool_size: 15
  max_overflow: 25

# Redis 配置
redis:
  max_connections: 15

# API 配置
api:
  workers: 6

# 监控配置
monitoring:
  enabled: true

# 服务配置
ai_service:
  enabled: true
  model: "gpt-3.5-turbo"
  max_tokens: 1500
  
document_processor:
  enabled: true
  max_file_size: 10485760  # 10MB
  
web_crawler:
  enabled: true
  max_pages: 200