# 默认配置文件
# 包含所有服务的基础配置

# 系统配置
system:
  name: "llmstxt-gen"
  version: "1.0.0"
  debug: false
  env: "development"
  
# 数据库配置
database:
  host: "localhost"
  port: 5432
  name: "llmstxt_gen"
  user: "postgres"
  password: ""
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Redis 配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  max_connections: 10

# API 服务配置
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  cors_origins: ["*"]
  cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_headers: ["*"]

# AI 服务配置
ai_service:
  enabled: true
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.7
  timeout: 30
  retry_attempts: 3

# 文档处理服务配置
document_processor:
  enabled: true
  max_file_size: 10485760  # 10MB
  supported_formats: ["txt", "md", "pdf", "docx"]
  processing_timeout: 300

# 网站爬取服务配置
web_crawler:
  enabled: true
  max_pages: 100
  delay: 1
  timeout: 30
  user_agent: "llmstxt-gen/1.0.0"
  follow_redirects: true

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  rotation: "midnight"

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
  performance_tracking: true

# 安全配置
security:
  secret_key: "your-secret-key-change-in-production-min-32-chars"
  jwt_secret: "your-jwt-secret-key-min-32-chars-required"
  jwt_algorithm: "HS256"
  jwt_expiration: 3600
  bcrypt_rounds: 12

# 文件存储配置
storage:
  type: "local"
  local_path: "data/storage"
  max_storage_size: 1073741824  # 1GB
  allowed_extensions: ["txt", "md", "pdf", "docx", "png", "jpg", "jpeg"]